# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 01:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pm', '0016_auto_20170504_0946'),
        ('lims', '0008_exttask_libtask_qctask_sampleinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barcode',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='sample',
        ),
        migrations.DeleteModel(
            name='Primer',
        ),
        migrations.AddField(
            model_name='exttask',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.SampleInfo', verbose_name='样品'),
        ),
        migrations.AddField(
            model_name='exttask',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='实验员'),
        ),
        migrations.AddField(
            model_name='libtask',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.SampleInfo', verbose_name='样品'),
        ),
        migrations.AddField(
            model_name='libtask',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='实验员'),
        ),
        migrations.AddField(
            model_name='qctask',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.SampleInfo', verbose_name='样品'),
        ),
        migrations.AddField(
            model_name='qctask',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='实验员'),
        ),
        migrations.AddField(
            model_name='sampleinfo',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pm.Project', verbose_name='项目'),
        ),
        migrations.AlterUniqueTogether(
            name='sampleinfo',
            unique_together=set([('project', 'name', 'receive_date')]),
        ),
        migrations.DeleteModel(
            name='Experiment',
        ),
    ]
