# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20170504_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-timestamp',), 'verbose_name': '通知管理', 'verbose_name_plural': '通知管理'},
        ),
    ]
