# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0012_auto_20170504_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='fin_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='尾款额'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='fis_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='首款额'),
        ),
    ]
