# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0009_auto_20170504_0946'),
        ('pm', '0016_auto_20170504_0946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='SequenceInfo',
        ),
        migrations.AddField(
            model_name='qcsubmit',
            name='sample',
            field=models.ManyToManyField(to='lims.SampleInfo', verbose_name='样品'),
        ),
        migrations.AddField(
            model_name='libsubmit',
            name='sample',
            field=models.ManyToManyField(to='lims.SampleInfo', verbose_name='样品'),
        ),
        migrations.AddField(
            model_name='extsubmit',
            name='sample',
            field=models.ManyToManyField(to='lims.SampleInfo', verbose_name='样品'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='init_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
